<a href="https://colab.research.google.com/github/steady-endeavor/study/blob/python_ML/2.4_numpy_%EA%B3%B5%EB%B6%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x = [1, 2, 5, 10]
print(x*3)

[1, 2, 5, 10, 1, 2, 5, 10, 1, 2, 5, 10]


In [2]:
y = np.array(x)
print(y*3)

[ 3  6 15 30]


In [3]:
z = list(y)
print(z)
print(type(y))
print(type(z))

[1, 2, 5, 10]
<class 'numpy.ndarray'>
<class 'list'>


In [5]:
y1 = np.array([1, 2, 3, 4])
y2 = np.array([10, 10, 100, 100])

print(y1+y2)
print(y1-y2)
print(y1*y2)
print(y1/y2)

[ 11  12 103 104]
[ -9  -8 -97 -96]
[ 10  20 300 400]
[0.1  0.2  0.03 0.04]


In [6]:
y1 = np.array([1,2,3,4])
a = 1000

print(y1+a)
print(y1-a)
print(y1*a)
print(y1/a)

[1001 1002 1003 1004]
[-999 -998 -997 -996]
[1000 2000 3000 4000]
[0.001 0.002 0.003 0.004]


In [7]:
list(y1) + list(y2)

[1, 2, 3, 4, 10, 10, 100, 100]

In [8]:
print(np.arange(6))
print(np.arange(1,7))
print(np.arange(1,20,3))
print(np.arange(1,4,0.5))

[0 1 2 3 4 5]
[1 2 3 4 5 6]
[ 1  4  7 10 13 16 19]
[1.  1.5 2.  2.5 3.  3.5]


In [10]:
import pandas as pd
import numpy as np

x = {'city': ['서울', '부산', '대구', '대전', '광주'],
     'population': [990, 350, 250, 154, 150],
     'temp': [13, 16, 14, 13, 15],
     'cars' :[300, 120, 80, 90, 70]}

df = pd.DataFrame(x)
df.set_index('city', inplace=True)
df


population  temp  cars
city                        
서울           990    13   300
부산           350    16   120
대구           250    14    80
대전           154    13    90
광주           150    15    70

In [11]:
z = df.values
print(z.shape)
z

(5, 3)


array([[990,  13, 300],
       [350,  16, 120],
       [250,  14,  80],
       [154,  13,  90],
       [150,  15,  70]])

In [14]:
print(list(df.columns))
print(list(df.index))

['population', 'temp', 'cars']
['서울', '부산', '대구', '대전', '광주']


In [15]:
df2 = pd.DataFrame(z)
df2

0   1    2
0  990  13  300
1  350  16  120
2  250  14   80
3  154  13   90
4  150  15   70

In [16]:
df2 = pd.DataFrame(z, index=df.index, columns=df.columns)
df2

population  temp  cars
city                        
서울           990    13   300
부산           350    16   120
대구           250    14    80
대전           154    13    90
광주           150    15    70

In [17]:
z[:3]

array([[990,  13, 300],
       [350,  16, 120],
       [250,  14,  80]])

In [18]:
z[:,[0,2]]

array([[990, 300],
       [350, 120],
       [250,  80],
       [154,  90],
       [150,  70]])

In [23]:
x1 = np.arange(0,12).reshape(4,3)
x2 = np.arange(100,112).reshape(4,3)
print(x1)
print(x2)
x1, x2

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[100 101 102]
 [103 104 105]
 [106 107 108]
 [109 110 111]]


(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), array([[100, 101, 102],
        [103, 104, 105],
        [106, 107, 108],
        [109, 110, 111]]))

In [25]:
x3 = np.concatenate((x1, x2))
x3

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

In [26]:
x3 = np.concatenate((x1, x2), axis=1)
x3

array([[  0,   1,   2, 100, 101, 102],
       [  3,   4,   5, 103, 104, 105],
       [  6,   7,   8, 106, 107, 108],
       [  9,  10,  11, 109, 110, 111]])

In [27]:
x = np.arange(48).reshape(6,8)
print(x)
np.savetxt('big.csv', x, fmt='%d', delimiter=',')

with open('big.csv') as f:
  print(f.read())

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
0,1,2,3,4,5,6,7
8,9,10,11,12,13,14,15
16,17,18,19,20,21,22,23
24,25,26,27,28,29,30,31
32,33,34,35,36,37,38,39
40,41,42,43,44,45,46,47



In [28]:
y = np.loadtxt('big.csv', delimiter=',')
y

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31.],
       [32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47.]])